export const ARGAO_BARANGAYS = [
  { "id": "brgy-alambijud", "name": "Alambijud", "lat": 9.951803, "lng": 123.517838, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-anajao", "name": "Anajao", "lat": 9.98623, "lng": 123.507351, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-apo", "name": "Apo", "lat": 9.989371, "lng": 123.521138, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-balaas", "name": "Balaas", "lat": 9.8768494, "lng": 123.4891452, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-balisong", "name": "Balisong", "lat": 9.839822, "lng": 123.554612, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-binlod", "name": "Binlod", "lat": 9.91514, "lng": 123.608709, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-bogo", "name": "Bogo", "lat": 9.859457, "lng": 123.572502, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-bug-ot", "name": "Bug-ot", "lat": 9.875266, "lng": 123.572384, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-bulasa", "name": "Bulasa", "lat": 9.927265, "lng": 123.616177, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-butong", "name": "Butong", "lat": 9.910115, "lng": 123.486492, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-calagasan", "name": "Calagasan", "lat": 9.901444, "lng": 123.49901, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-canbantug", "name": "Canbantug", "lat": 9.874843, "lng": 123.502075, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-canbanua", "name": "Canbanua", "lat": 9.88525, "lng": 123.598033, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-cansuje", "name": "Cansuje", "lat": 9.923965, "lng": 123.524405, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-capio-an", "name": "Capio-an", "lat": 9.956125, "lng": 123.574795, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-casay", "name": "Casay", "lat": 9.8401504, "lng": 123.5624139, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-catang", "name": "Catang", "lat": 9.896691, "lng": 123.555891, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-colawin", "name": "Colawin", "lat": 9.974139, "lng": 123.551302, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-conalum", "name": "Conalum", "lat": 9.909844, "lng": 123.528133, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-guiwanon", "name": "Guiwanon", "lat": 9.962298, "lng": 123.619202, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-gutlang", "name": "Gutlang", "lat": 9.967627, "lng": 123.562013, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-jampang", "name": "Jampang", "lat": 9.911746, "lng": 123.592851, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-jomgao", "name": "Jomgao", "lat": 9.891384, "lng": 123.579886, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-lamacan", "name": "Lamacan", "lat": 9.8784487, "lng": 123.5950192, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-langtad", "name": "Langtad", "lat": 9.890637, "lng": 123.606577, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-langub", "name": "Langub", "lat": 9.973687, "lng": 123.573834, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-lapay", "name": "Lapay", "lat": 9.886958, "lng": 123.550291, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-lengigon", "name": "Lengigon", "lat": 9.976599, "lng": 123.543895, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-linut-od", "name": "Linut-od", "lat": 9.889077, "lng": 123.486682, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-mabasa", "name": "Mabasa", "lat": 9.932279, "lng": 123.563671, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-mandilikit", "name": "Mandilikit", "lat": 9.948634, "lng": 123.572836, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-mompeller", "name": "Mompeller", "lat": 9.978938, "lng": 123.529101, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-panadtaran", "name": "Panadtaran", "lat": 9.895414, "lng": 123.571067, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-poblacion", "name": "Poblacion", "lat": 9.8802091, "lng": 123.605901, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-sua", "name": "Sua", "lat": 9.940475, "lng": 123.578246, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-sumaguan", "name": "Sumaguan", "lat": 9.96315, "lng": 123.594009, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-tabayag", "name": "Tabayag", "lat": 9.888668, "lng": 123.531628, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-talaga", "name": "Talaga", "lat": 9.849565, "lng": 123.565467, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-talaytay", "name": "Talaytay", "lat": 9.892641, "lng": 123.597716, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-talo-ot", "name": "Talo-ot", "lat": 9.954835, "lng": 123.618311, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-tiguib", "name": "Tiguib", "lat": 9.872541, "lng": 123.545252, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-tulang", "name": "Tulang", "lat": 9.960764, "lng": 123.511678, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-tulic", "name": "Tulic", "lat": 9.869362, "lng": 123.585527, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-ubaub", "name": "Ubaub", "lat": 9.93876, "lng": 123.535109, "type": "barangay", "address": "Argao, Cebu" },
  { "id": "brgy-usmad", "name": "Usmad", "lat": 9.909827, "lng": 123.555864, "type": "barangay", "address": "Argao, Cebu" },
];

export const ARGAO_HELP_FACILITIES = [
  { "id": "fac-isidroc-kintanarmemorialhospital", "name": "Isidro C. Kintanar Memorial Hospital", "lat": 9.856293, "lng": 123.570756, "type": "hospital", "phone": "(032) 485 8599", "address": "Natalio Bacalso Avenue, Argao, Cebu" },
  { "id": "fac-pantinoplemedicalclinic-hospital", "name": "Pantinople Medical Clinic & Hospital", "lat": 9.883332, "lng": 123.602363, "type": "hospital", "phone": null, "address": "Argao, Cebu" },
  { "id": "fac-southwesternunivesity-swu-argaocommunityhospital", "name": "SWU-Argao Community Hospital", "lat": 9.876684, "lng": 123.597411, "type": "hospital", "phone": null, "address": "Argao, Cebu" },
  { "id": "fac-anajaobarangayhealthstation", "name": "Anajao Barangay Health Station", "lat": 9.986107, "lng": 123.506924, "type": "clinic", "phone": null, "address": "Anajao, Argao, Cebu" },
  { "id": "fac-municipalhealthoffice", "name": "Argao Municipal Health Office", "lat": 9.877329, "lng": 123.599016, "type": "clinic", "phone": null, "address": "Argao, Cebu" },
  { "id": "fac-argaoprimarycarefacility-", "name": "Argao Primary Care Facility I", "lat": 9.880694, "lng": 123.608901, "type": "clinic", "phone": "+63 323677331", "address": "Argao, Cebu" },
  { "id": "fac-bayabashealthstation", "name": "Bayabas Health Station", "lat": 9.919027, "lng": 123.496793, "type": "clinic", "phone": null, "address": "Bayabas, Argao, Cebu" },
  { "id": "fac-bulasabarangayhealthcenter", "name": "Bulasa Barangay Health Center", "lat": 9.927469, "lng": 123.616439, "type": "clinic", "phone": null, "address": "Argao, Cebu" },
  { "id": "fac-butongbarangayhealthstation", "name": "Butong Barangay Health Station", "lat": 9.907282, "lng": 123.483586, "type": "clinic", "phone": null, "address": "Butong, Argao, Cebu" },
  { "id": "fac-cansujebarangayhealthstation", "name": "Cansuje Barangay Health Station", "lat": 9.924722, "lng": 123.524127, "type": "clinic", "phone": null, "address": "Cansuje, Argao, Cebu" },
  { "id": "fac-jampangbarangayhealthcenter", "name": "Jampang Barangay Health Center", "lat": 9.911535, "lng": 123.592793, "type": "clinic", "phone": null, "address": "Argao, Cebu" },
  { "id": "fac-langubbarangayhealthstation", "name": "Langub Barangay Health Station", "lat": 9.973343, "lng": 123.573945, "type": "clinic", "phone": null, "address": "Langub, Argao, Cebu" },
  { "id": "fac-lengigonbarangayhealthcenter", "name": "Lengigon Barangay Health Center", "lat": 9.976599, "lng": 123.543895, "type": "clinic", "phone": null, "address": "Argao, Cebu" },
  { "id": "fac-mabasabarangayhealthstation", "name": "Mabasa Barangay Health Station", "lat": 9.932238, "lng": 123.563579, "type": "clinic", "phone": null, "address": "Argao, Cebu" },
  { "id": "fac-mandilikitbarangayhealthcenter", "name": "Mandilikit Barangay Health Center", "lat": 9.948654, "lng": 123.573256, "type": "clinic", "phone": null, "address": "Argao, Cebu" },
  { "id": "fac-talagabarangayhealthcenter", "name": "Talaga Barangay Health Center", "lat": 9.849564, "lng": 123.567248, "type": "clinic", "phone": null, "address": "Argao, Cebu" },
  { "id": "fac-tulangbarangayhealthcenter", "name": "Tulang Barangay Health Center", "lat": 9.958376, "lng": 123.509978, "type": "clinic", "phone": null, "address": "Argao, Cebu" },
  { "id": "fac-tulicbarangayhealthstation", "name": "Tulic Barangay Health Station", "lat": 9.869076, "lng": 123.585785, "type": "clinic", "phone": null, "address": "Natalio Bacalso Avenue, Argao, Cebu" },
  { "id": "fac-ubaubbarangayhealthcenter", "name": "Ubaub Barangay Health Center", "lat": 9.939117, "lng": 123.535004, "type": "clinic", "phone": null, "address": "Argao, Cebu" },
  { "id": "fac-argaopolicestation", "name": "Argao Police Station", "lat": 9.880793, "lng": 123.608792, "type": "police", "phone": "911", "address": "Ortega Street, Argao, Cebu" },
  { "id": "fac-argaofirestation", "name": "Argao Fire Station", "lat": 9.881969, "lng": 123.600326, "type": "fire", "phone": "911", "address": "Isidro Kintanar Street, Argao, Cebu" },
  { "id": "fac-balaylungsodsaargao", "name": "Balay Lungsod sa Argao", "lat": 9.881217, "lng": 123.608699, "type": "help", "phone": null, "address": "Osmeña Street, Argao, Cebu" },
];

export const MAP_TYPE_META = {
  "hospital": { "color": "#D32F2F", "label": "Hospital", "icon": "medkit", "responseNote": "Hospital care for injuries, illnesses, and medical emergencies." },
  "clinic": { "color": "#00897B", "label": "Clinic", "icon": "pulse", "responseNote": "Health station for checkups, first aid, and medical consultations." },
  "police": { "color": "#294880", "label": "Police Station", "icon": "shield-checkmark", "responseNote": "Nearest police assistance for public safety concerns." },
  "fire": { "color": "#F4511E", "label": "Fire Station", "icon": "flame", "responseNote": "Nearest fire response for fire and emergency incidents." },
  "barangay": { "color": "#2E7D32", "label": "Barangay", "icon": "home", "responseNote": "Barangay officials can assist residents and visitors with local concerns." },
  "help": { "color": "#7B1FA2", "label": "Help Station", "icon": "help-buoy", "responseNote": "Municipal office for public assistance and social services." },
};

export const MAP_TYPE_BY_LABEL = {
  "Hospital": "hospital",
  "Clinic": "clinic",
  "Police Station": "police",
  "Fire Station": "fire",
  "Barangay": "barangay",
  "Help Station": "help",
};

export const MAP_FILTER_TYPES = ["All","Hospital","Clinic","Police Station","Fire Station","Barangay","Help Station"];
